defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/openjdk:8-jdk
  environment:
    MAVEN_OPTS: -Xmx3200m
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: wget https://github.com/thewilly/UDocs/raw/master/hsqldb-2.4.0.zip;
              unzip hsqldb-2.4.0.zip;
              cd hsqldb-2.4.0/hsqldb/bin/;
              sh runServer.sh &;
              mvn clean install;
      - run: bash <(curl -s https://codecov.io/bash)
  unit-tests:
    <<: *defaults
    steps:
      - checkout
      - run: mvn test -Dgroups="com.uniovi.categories.UnitTest"

  integration-tests:
    <<: *defaults
    steps:
      - checkout
      - run: mvn test -Dgroups="com.uniovi.categories.IntegrationTest"
workflows:
  version: 2
  build_and_tests:
    jobs:
      - build
      - unit-tests
      - integration-tests:
          requires:
            - build
